### ISSUE TITLE
Feature request: keep track of directly assigned score

### ISSUE THREAD

**Issue by firmart** [sp1ff/elfeed-score#10]
Adjust `elfeed-score-score` and `elfeed-score-explain` in such a way that it takes accounts for manual scoring. Currently, all manually added score of an entry are erased when calling `elfeed-score-score`.

**Comment by sp1ff** [comment]
IOW, if you manually set a score, it should not be overwritten by `elfeed-score-score`-- makes sense; I'll get on it.
BTW, thanks for all the issues! My day job has kept me busy over the past week, but I'll get on 'em.

**Comment by sp1ff** [comment]
Closed in 0.7.9
