### ISSUE TITLE
Score based on link content

### ISSUE THREAD

**Issue by TheLugal** [sp1ff/elfeed-score#11]
Is there a way to score based on the link of an entry?

For clarity:
Say I subscribe to the feed `example.com/feed.rss` that contains items that links to articles like `example.com/news/content.html` and `example.com/sports/content.html`. Can I in this instance have one score for news-links and another for sports-links?

**Comment by sp1ff** [comment]
Hi there. Trying to understand the ask: do you mean you want to score against the "Link:" contents when you show an entry? Like this:

> Title: Fooblah
> Author: [unknown]
>...
> Link: https://www.google.com/?url=...
>
> Blahblahblah
mode line: *elfeed-entry*

If so no, but only because no one's asked-- it'd be easy to whip up. Let me know

**Comment by TheLugal** [comment]
Hello! Yes, I believe we're on the same page. I'd be very grateful if it isn't too much of a hassle to add in. :)

**Comment by sp1ff** [comment]
Not at all... I've got some other changes in flight (as well as a day job), but will try to get to it in the next week or so.

**Comment by sp1ff** [comment]
Alright well, it was a bit more than a week, but the latest release lands this @TheLugal -- take a look & tell me if this works for you!

**Comment by TheLugal** [comment]
Oh, sorry, I missed your previous reply!

That was quicker than I anticipated. I won't have the time to upgrade before the weekend, but from the commit it seems to be exactly what I was looking for. Thanks for adding it in!

**Comment by sp1ff** [comment]
Closing this in light of #14
