### ISSUE TITLE
elfeed.score is overwritten by elfeed-score-score-search

### ISSUE THREAD

**Issue by vikasrawal** [sp1ff/elfeed-score#15]
I am sorry, I do not know if I have misunderstood the workflow for using elfeed-score.

I presume elfeed-score has to be maintained manually. I wrote the following in my elfeed.score:

```
((version 7)
 ("title")
 ("content")
 ("title-or-content"
  (:text "kerala" :value 1500 :type w
  :date 1612278560.2936354 :hits 46)
  )
 ("tag")
 ("authors")
 ("feed")
 ("link")
 (mark nil)
 ("adjust-tags"))

```

But when I run elfeed-score-score-search, it just removes the rule/rules that I have added.

I am unable to understand how am I supposed to create and save these rules.

Would appreciate help.

Vikas

**Comment by C-J-Cundy** [comment]
Hi, this is discussed here: https://github.com/sp1ff/elfeed-score/issues/13, it seems like this behaviour of often overwriting the score file will be changed in future.

I generally just make sure to close all elfeed buffers except the score file before I edit the score file to avoid it being overwritten.

**Comment by sp1ff** [comment]
That's right, Chris. @vikasrawal ... I'm assuming you're [u/birdhana](https://www.reddit.com/user/birdhana/) on Reddit, with whom I chatted [here](https://www.reddit.com/r/emacs/comments/lsq8h9/ann_elfeedscore_07/) and that this issue is resolved.
Feel free to re-open if it is not!
