### ISSUE TITLE
Everything has 0 score

### ISSUE THREAD

**Issue by vikasrawal** [sp1ff/elfeed-score#16]
Somehow, elfeed-score has stopped scoring the items correctly. Everything has a zero score, and my rules are just ignored. It used to work earlier, but has stopped working after I rewrote my .emacs.d, and reinstalled all the emacs packages.

Even after I reload my elfeed.score file (=l), nothing changes. Everthing still has a 0 score.

I am not sure how to debug this.

**Comment by sp1ff** [comment]
@vikasrawal I guess you resolved this yourself?

**Comment by vikasrawal** [comment]
I did. Sorry, it was just an error in my config files. Thank you.

**Comment by k4r4b3y** [comment]
> I did. Sorry, it was just an error in my config files. Thank you.

Would be nice if you also mentioned what error in your config file you resolved.  I am also seeing only score zero in elfeed main UI, however, doing `elfeed-score-explain` shows the correct scoring.

Edit: noticed that existing items in the elfeed show up as score zero, even though `elfeed-score-explain` reports their correct, non-zero score.  Hitting `G` to fetch new articles gets `elfeed-score` to be able to display scores in the elfeed UI correctly, but, *for the new items*.
