### ISSUE TITLE
Error running elfeed-score-enable

### ISSUE THREAD

**Issue by Anirudh-C** [sp1ff/elfeed-score#17]
When I run `(elfeed-score-enable)` I get the error "Missing mandatory field title-value"

**Comment by sp1ff** [comment]
@Anirudh-C I take it you fixed this? The 0.9 release included stricter validation on read. Sorry for the inconvenience, but the good news is that that rule was silently failing up until now!

**Comment by Anirudh-C** [comment]
> @Anirudh-C I take it you fixed this? The 0.9 release included stricter validation on read. Sorry for the inconvenience, but the good news is that that rule was silently failing up until now!

Yes I realised the problem with my score file just as I created the issue.
