### ISSUE TITLE
possibility to run a function on an entry for scoring

### ISSUE THREAD

**Issue by jkitchin** [sp1ff/elfeed-score#19]
Is it possible to run a function on an entry that is responsible for computing a score? I guess you would implement it as a separate category of rules.

Maybe something like this
```
(:function func :comment "Computes the score from the word count")
```
The function would be called with something like this:

`(funcall func entry)`

and it would be expected to return a numeric score. The main thing I want to be able to do is

compare an entry to entries with a specific tag somehow, e.g. if it is similar to them it gets a higher score, or if it is similar to entries I tagged as not interesting, a lower score.

Maybe there are other things too, e.g. fancier tagging or something. WDYT?

**Comment by sp1ff** [comment]
Hey John-- I like it. One thought-- scoring is tightly coupled to explaining. See [here](https://github.com/sp1ff/elfeed-score/blob/master/elfeed-score-scoring.el#L212), for instance. Skimming the code quickly, I guess the `:function` could be used for both purposes.
Let me take a crack at it-- I might ping you to give the new code a whirl.

**Comment by jkitchin** [comment]
Maybe so, maybe the function should return a contribution to the score, and a string that is an explanation. I would guess this will generally be less explainable, since I am thinking of using things like tf-idf for similarity, or bag-of-words and Jaccard similarity.

**Comment by sp1ff** [comment]
Maybe it's enough to say something like "this contribution of x points was from the user-defined function `your-cool-scoring-function' on line thus-and-such of your score file".

It occurred to me today: the function will just return a contribution-- not take-over scoring duties entirely, right?

**Comment by jkitchin** [comment]
yes, I think it should just be a contribution, so you can still have all the rules if you also want them. Or if you only use a function (or set of functions), then they will be what leads to the accumulated score.

**Comment by sp1ff** [comment]
@jkitchin made an alpha release [here](https://github.com/sp1ff/elfeed-score/releases/tag/1.2.0) in case you want to try it. I'll let it bake a bit in my own Emacs instance before merging.

**Comment by sp1ff** [comment]
No issues; merged & released. Closing.

**Comment by jkitchin** [comment]
Thanks. It is working great. Now to put it to work!  I am using it like this. I use two tags, discard and star to mark entries I want to see less of and more of. Then, I get all the words from each group,  and remove the common words and stop words from each one. Finally, for new entries, I get a count of how many words in it match the discard list, and subtract that from the score. Another function gets a count of how many words match the starred list, and adds that to the score.  It is simple, but helpful so far.

**Comment by sp1ff** [comment]
That's interesting, since I too am considering "auto-scoring" mechanisms. I had thought to look at behavior like marking entries as read without looking at them (indicating a lack of interest), or opening in a browser (indicating interest). Can I look forward to a blog post on your work?

**Comment by jkitchin** [comment]
One day I will probably write about it, when I like what it does! it is pretty tricky, the number of priority things is very small compared to what I don't want to see. I am hoping to get something more like a naive bayes classifier going, but preliminary efforts have not been good...
