### ISSUE TITLE
Key duplication in elfeed-score-map 

### ISSUE THREAD

**Issue by qingshuizheng** [sp1ff/elfeed-score#21]
https://github.com/sp1ff/elfeed-score/blob/38988ebdbc335f990e9a90042141f18e3fc3ddb1/elfeed-score.el#L197-L198
Hi @sp1ff , I think this is a typo?

**Comment by sp1ff** [comment]
Nah I totally meant to do that ;)
Fix on the way.

**Comment by sp1ff** [comment]
Fixed in 1.2.2. Thanks!

**Comment by qingshuizheng** [comment]
> Fixed in 1.2.2. Thanks!

Awesome! Thanks!
