### ISSUE TITLE
`elfeed-score-scoring-score-entry` should be added to the end of `elfeed-new-entry-hook`

### ISSUE THREAD

**Issue by swflint** [sp1ff/elfeed-score#30]
Or it should be configurable.

Because of how `add-hook` operates, if elfeed score is enable after all other elfeed configuration is completed (including addition of taggers via `elfeed-make-tagger`) it will be the first thing run on a new entry.

**Comment by sp1ff** [comment]
Good point... but I don't like having the behavior of `elfeed-score-enable` depend on a customization variable. What do you think of making the depth a parameter to the function?

**Comment by swflint** [comment]
I like that idea. I've updated #31 to use that instead.

**Comment by sp1ff** [comment]
Closed in 1.2.6
