### ISSUE TITLE
Parent dirs in elfeed-score-rule-stats-file are not created automatically

### ISSUE THREAD

**Issue by yantar92** [sp1ff/elfeed-score#32]
When I try to set `elfeed-score-rule-stats-file` to a full path in a non-existing directory, elfeed-score errs, instead of creating that directory.

**Comment by sp1ff** [comment]
Got a stack trace? Error message?

**Comment by yantar92** [comment]
Michael ***@***.***> writes:

> Got a stack trace? Error message?

1. (setq elfeed-score-rule-stats-file "/home/yantar92/.emacs.d/var/elfeed/score/score-rule-stats.eld")

   ~/.emacs.d/var/elfeed/score directory does not exist.

2. Do something in elfeed

3.

Debugger entered--Lisp error: (error "/home/yantar92/.emacs.d/var/elfeed/score/: no such directory")
  (error "%s: no such directory" "/home/yantar92/.emacs.d/var/elfeed/score/")
  (elfeed-score-rule-stats--sexp-to-file (:version 1 :stats #<hash-table equal 6/65 0x1560cb87daf3 ...>) "/home/yantar92/.emacs.d/var/elfeed/score/score-rul..." ";;; Elfeed score rule stats file DO NOT EDIT      ...")
  (elfeed-score-rule-stats-write "/home/yantar92/.emacs.d/var/elfeed/score/score-rul...")
  (elfeed-score-rule-stats-update-hook "https://habr.com/ru/rss/company/ruvds/blog/?fl=ru")
  (run-hook-with-args elfeed-score-rule-stats-update-hook "https://habr.com/ru/rss/company/ruvds/blog/?fl=ru")
  (#f(compiled-function (status) #<bytecode -0x94a2bba2247cae1>) nil)
  (#f(compiled-function (status) #<bytecode 0xee460ebc46ef954>) nil)
  (elfeed-curl--fail-callback #<buffer  *curl*-891389> #f(compiled-function (status) #<bytecode 0xee460ebc46ef954>))
  (apply elfeed-curl--fail-callback (#<buffer  *curl*-891389> #f(compiled-function (status) #<bytecode 0xee460ebc46ef954>)))
  (timer-event-handler [t 25791 30676 458315 nil elfeed-curl--fail-callback (#<buffer  *curl*-891389> #f(compiled-function (status) #<bytecode 0xee460ebc46ef954>)) nil 868000 nil])


-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by sp1ff** [comment]
Should be fixed.
