### ISSUE TITLE
Feature Request: `elfeed-score-explain` function

### ISSUE THREAD

**Issue by C-J-Cundy** [sp1ff/elfeed-score#5]
I've been using elfeed-score for quite a few months now, and it's working brilliantly. 

One feature that would be really useful is some sort of interactive 'explain' function. At the moment, I have an elfeed.score file which is almost 500 lines long, and so sometimes it's a bit of a mystery why a particular entry that I expect to have a high score has a low score. It would be really useful to be able to press e.g. `= e` and have a list of `(match text, score contribution)` pop up in the minibuffer, in a similar way that currently I can press `= g` and have the entry's score pop up. 

I know it's possible to set the debug state and look at the log to see this, but having it on an interactive function would make the workflow much easier. 

I took a quick look but couldn't quite see how to get this to work.

**Comment by sp1ff** [comment]
First, apologies for missing this.
Second, that's a great idea. I've always used "debug" logging for this purpose, but the resulting firehose of log messages is tough to dig through. 
Do you think it should be displayed in the minibuffer, tho? This list *could* get long, and if you're debugging an issue, you might want to keep the info around (yes, if we use the minibuffer, you could go digging around in `*Messages*`, but still). In the other reporting methods, such as `elfeed-score-display-rules-by-last-match`, I use (and re-use) a buffer via `with-current-buffer-window`. So with this approach, the first time you hit "=e" a new buffer, named something like `*elfeed-score explanation*` would be created & displayed in the current frame, containing the output you're describing. I suppose it could be a configuration option.

**Comment by C-J-Cundy** [comment]
Having the results pop up in a new buffer would be a great idea. It definitely makes sense to keep the info around for debugging purposes

**Comment by sp1ff** [comment]
New code pushed on branch `explain-score`-- check it out.

**Comment by C-J-Cundy** [comment]
This is great! It has already helped me debug a few oddly-scored entries.
Could be nice for elfeed-score-explain-entry to be bound in the keymap by default -- maybe `= x` ?

**Comment by sp1ff** [comment]
New implementation pushed last night-- take a look. I'm using it locally; will let it "burn in" for a few days before merging this branch & releasing.

**Comment by C-J-Cundy** [comment]
I had a go with the latest version, it looks good.
There are two functions that are quite similar, `elfeed-score-explain-entry`, and `elfeed-score-explain`. 
I tried calling `elfeed-score-explain-entry` while over an entry and it threw an error, but `elfeed-score-explain` works.
If elfeed-score-explain-entry is not supposed to be called by the end user, it could make sense to not make it interactive?

**Comment by sp1ff** [comment]
Hmph-- good catch. Fixed, merged & released! Closing this out.
