### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by firmart** [sp1ff/elfeed-score#6]
In the Readme, 
1. (Introduction) the sample elfeed.score file has a key "author". It should be "author**s**".
2. There is a link to Elfeed whose the domain is `gitub.com` instead of `github.com`.

**Comment by firmart** [comment]
Actually the entry of `authors` is not valid either. It should be
` ("authors"
  ("Leto Sapunar" 500 S 1597068910.0))`. I made this remark because people may clone the sample `elfeed.score` to test this package quickly.

**Comment by sp1ff** [comment]
Fixed by that commit
