### ISSUE TITLE
Documentation: `elfeed-score-explain`

### ISSUE THREAD

**Issue by firmart** [sp1ff/elfeed-score#9]
The docstring of `elfeed-score-explain` is a copy-paste of `elfeed-score-score`.

https://github.com/sp1ff/elfeed-score/blob/5fff4152bdb2a5f38ab83f7fa6b2943647935f94/elfeed-score.el#L1705-L1710

https://github.com/sp1ff/elfeed-score/blob/5fff4152bdb2a5f38ab83f7fa6b2943647935f94/elfeed-score.el#L1838-L1843

**Comment by sp1ff** [comment]
Damn, that's embarrassing.

**Comment by sp1ff** [comment]
Fixed by the above commit.
